// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Article struct {
	ID        int64
	ProfileID int64
	Title     string
	Kind      string
	Spec      string
	Content   string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ArticleChunk struct {
	ID        int64
	ArticleID sql.NullInt64
	Offset    sql.NullInt64
	Length    sql.NullInt64
}

type ArticleTag struct {
	ArticleID sql.NullInt64
	Tag       sql.NullString
}

type Config struct {
	Key       string
	Value     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Profile struct {
	ID        int64
	Name      string
	Emoji     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
